NHSDigital/summary-care-record-api

- docker/README.md
- docker/clear-docker.sh
- docker/docker-compose.yml
- docker/docker/Dockerfile
- docker/docker/build-image.sh
- docker/restart-service.sh
- docker/start-local-environment.sh
> NIAD-437: Local env setup docker and scripts

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/AcsTest.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/AcsController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/AcsService.java
- docker/service/src/main/resources/templates/has_resource_permissions.mustache
> NIAD-469:  Check ACS consent when updating SCR

- docker/service/src/integration-test/resources/responses/MCCI_IN010000UK13.xml
- docker/service/src/integration-test/resources/responses/get_resource_permissions.xml
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/GpSummary.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/AcsService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/ScrService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/AcsResponseParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/GpSummaryParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/TemplateUtils.java
- docker/service/src/main/resources/templates/REPC_RM150007UK05.mustache
- docker/service/src/main/resources/templates/get_resource_permissions.mustache
- docker/service/src/main/resources/templates/has_resource_permissions.mustache
> NIAD-470: Send correct SCR request to Spine

- azure/azure-build-pipeline.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- azure/project.yml
- specification/summary-care-record.yaml
> Migrate to centralised YAML pipelines

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/component/ScrTest.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
> NIAD-471: Return 504 if there is no result after polling

- docker/service/src/main/java/uk/nhs/adaptors/scr/fhirmappings/CompositionMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/gpsummarymodels/Presentation.java
- docker/service/src/main/resources/templates/REPC_RM150007UK05.mustache
> NIAD-557: GPSummary Mapping Fix

- .github/workflows/pr-lint.yaml
- proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
- proxies/sandbox/apiproxy/proxies/default.xml
> NIAD-683: ping endpoint

- docker/README.md
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ConversationIdFilter.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ConversationIdFilterConfig.java
- docker/service/src/main/resources/application.yml
- docker/service/src/main/resources/logback.xml
> NIAD-647: Added X-Correlation-ID header and into logs

- docker/service/src/main/resources/application.yml
- ecs-proxies-deploy.yml
> NIAD-648 fixing env vars

- Makefile
- azure/project.yml
- docker/service/Dockerfile
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/ScrService.java
- docker/service/src/main/resources/application.yml
- ecs-proxies-deploy.yml
- proxies/live/apiproxy/policies/AssignMessage.PopulateAsidFromApp.xml
- proxies/live/apiproxy/targets/scr-target.xml
> NIAD-631 populate ASID in apigee

- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/FhirController.java
> NIAD-647: Copy MDC context to task thread

- docker/docker-compose.yml
- docker/docker/spine-mock/stubs/mappings/no-result-scr-get.json
- docker/docker/spine-mock/stubs/mappings/no-result-scr-post.json
- docker/service/gradle/wrapper/gradle-wrapper.properties
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/GatewayTimeoutException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/NHSCodings.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/NoSpineResultException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/ScrTimeoutException.java
- docker/service/src/main/resources/application.yml
> NIAD-712: Return 504 with proper OperationOutcome if there is no result after polling

- ecs-proxies-deploy.yml
> APM-0000 Fix ecs-proxies-deploy

- docker/docker/spine-mock/stubs/mappings/bad-response-scr-post.json
> Added bad response for testing 502

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/component/ScrTest.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/BadGatewayException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/BadRequestException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/NoSpineResultException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/OperationOutcomeError.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/ScrTimeoutException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/OperationOutcomeUtils.java
> NIAD-711: Proper 400 OperationOutcome

- docker/service/src/integration-test/resources/application.yml
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ScrConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/SpineConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/ScrHttpClientBuilder.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/OperationOutcomeUtils.java
- ecs-proxies-deploy.yml
> NIAD-648 better 500 operation outcome

- docker/service/src/integration-test/resources/bundle.fhir.json
- specification/summary-care-record.yaml
> NIAD-459: Create OpenApi specification for POST SCR API

- docker/service/build.gradle
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/component/ScrControllerTest.java
- docker/service/src/integration-test/resources/application.yml
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineHttpClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ScrConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/SpineConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/FhirController.java
- docker/service/src/main/resources/application.yml
- docker/service/src/main/resources/logback.xml
- ecs-proxies-deploy.yml
> NIAD-648: deploy fix

- docker/service/src/integration-test/resources/bundle.fhir.json
- docker/service/src/main/resources/templates/REPC_RM150007UK05.mustache
change hl7 message to correct formatting, update nhs no and uuid to valid ones for spine to recognize
> NIAD-739: SCR adjust hl7 sent to spine

- azure/azure-release-pipeline.yml
> NIAD-459 make OpenAPI Spec visible

- proxies/live/apiproxy/policies/AssignMessage.CatchallErrorMessage.xml
- proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
- proxies/live/apiproxy/policies/KeyValueMapOperations.GetCommonSecureVariables.xml
- proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/live/apiproxy/policies/VerifyApiKey-Header.xml
- proxies/live/apiproxy/policies/javascript.SetStatusResponse.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
- proxies/live/apiproxy/targets/scr-target.xml
> NIAD-683: Status endpoint

- azure/azure-release-pipeline.yml
> NIAD-509 deploy sandbox to int

- proxies/live/apiproxy/targets/scr-target.xml
> NIAD-509 CatchAllError policy should not override expected errors

- azure/azure-build-pipeline.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
> apm-1351: use pre-release utils for aws agents

- specification/components/examples/DocumentReferenceBundle.json
- specification/components/schemas/DocumentReference.yaml
- specification/components/schemas/DocumentReferenceBundle.yaml
- specification/components/schemas/PatientEntry.yaml
- specification/summary-care-record.yaml
> NIAD-575 Get SCR ID - OpenAPI spec

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/component/ScrControllerTest.java
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/component/ScrTest.java
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/GetScrIdUAT.java
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/UploadScrUAT.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SandboxSpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/SpineClientContract.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ConversationIdFilter.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/RequestIdFilter.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/UuidValidationFilter.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/consts/ScrHttpHeaders.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/consts/SpineHttpHeaders.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/FhirController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/GetScrController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/RequestData.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/UploadScrService.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/clients/SpineClientTest.java
- proxies/live/apiproxy/policies/AssignMessage.MissingUserRoleIDHeader.xml
- proxies/live/apiproxy/targets/scr-target.xml
- specification/summary-care-record.yaml
> Niad 742 nhsd session urid

- specification/components/examples/SetPermission.json
- specification/components/schemas/Parameter.yaml
- specification/components/schemas/Parameters.yaml
- specification/components/schemas/PartNhsNumber.yaml
- specification/components/schemas/PartPermissionCode.yaml
- specification/summary-care-record.yaml
> Niad 701 acs open api spec

- specification/components/examples/AuditEvent.json
- specification/components/schemas/AuditEvent.yaml
- specification/components/schemas/agentElement.yaml
- specification/components/schemas/coding.yaml
- specification/components/schemas/codingElement.yaml
- specification/summary-care-record.yaml
> Niad 700/send alert oas

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SandboxSpineClient.java
> NIAD-703 Add sandbox method for sendAlert

- docker/service/src/main/java/uk/nhs/adaptors/scr/fhirmappings/CompositionMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/fhirmappings/ConditionMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/fhirmappings/ObservationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/GpSummary.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/DateUtil.java
- proxies/sandbox/apiproxy/targets/sandbox.xml
- specification/components/schemas/AuditEvent.yaml
- specification/components/schemas/UploadBundle.yaml
- specification/components/schemas/agentElement.yaml
- specification/components/schemas/compositionIdentifier.yaml
- specification/summary-care-record.yaml
> NIAD-592 Sandbox + OpenAPI doc

- Makefile
- scripts/deploy_proxy.sh
- scripts/deploy_spec.sh
> NIAD-592 Publishing OAS

- azure/azure-release-pipeline.yml
- proxies/sandbox/apiproxy/policies/KeyValueMapOperations.GetCommonSecureVariables.xml
- proxies/sandbox/apiproxy/policies/RaiseFault.401Unauthorized.xml
- proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/sandbox/apiproxy/policies/javascript.SetStatusResponse.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/resources/jsc/SetStatusResponse.js
> NIAD-1000 enable monitoring

- specification/summary-care-record.yaml
> NIAD-592 SCR OAS tags

- package.json
- specification/summary-care-record.yaml
> NIAD-592 removed tags

- azure/project.yml
- docker/service/src/test/java/uk/nhs/adaptors/scr/controllers/utils/UrlUtilsTest.java
- specification/components/examples/DocumentReferenceBundle.json
- specification/components/schemas/DocumentReference.yaml
- specification/summary-care-record.yaml
> NIAD-1001 change SCR basepath to end with /FHIR/R4

- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/AcsController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequest.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/AcsService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/UploadScrService.java
> NIAD-699: Move ACS validation to external validator class

- Makefile
- azure/azure-release-pipeline.yml
- scripts/populate_ssm_parameters.sh
> NIAD-1042 Deploy to REF env

- products/all.yml
- products/ref.yml
> NIAD-1045 allow 40 tps

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/identity/IdentityServiceClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/AcsController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/AlertController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/GetScrController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/SendScrController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/AlertService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/UploadScrService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/DateUtil.java
> NIAD-508 Fixed DateTime conversion + additional logging

- scripts/populate_ssm_parameters.sh
> NIAD-1091 change Spine REF URL AWS source param

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/GpSummaryMapper.java
> NIAD-1100 handling optional replacementOf element

- specification/components/schemas/PartPermissionCode.yaml
> NIAD-1109 workaround for displaying Yes/No values

- specification/components/examples/GetScrBundle.json
- specification/components/examples/UploadScrBundle.json
- specification/components/schemas/CompositionEntry.yaml
- specification/components/schemas/DeviceEntry.yaml
- specification/components/schemas/DocumentReference.yaml
- specification/components/schemas/EncounterParticipantEntry.yaml
- specification/components/schemas/OrganizationEntry.yaml
- specification/components/schemas/PractitionerEntry.yaml
- specification/components/schemas/PractitionerRoleEntry.yaml
- specification/components/schemas/RelatedPersonEntry.yaml
- specification/components/schemas/compositionAuthor.yaml
- specification/components/schemas/compositionSubject.yaml
> NIAD-1114 OAS examples update

- CHANGELOG.md
- docker/service/src/integration-test/resources/uat/responses/event-list-query/noConsent.xml
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/EventListQueryResponse.java
> NIAD-1131 check ACS consent on SCR upload

- docker/service/src/integration-test/resources/bundle.fhir.json
- docker/service/src/integration-test/resources/uat/get_scr/success/1-basic.response.json
- docker/service/src/integration-test/resources/uat/upload_scr/no_consent/1-dissent.request.json
- docker/service/src/integration-test/resources/uat/upload_scr/success/1-basic.request.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/GpSummaryMapper.java
- specification/components/examples/GetScrBundle.json
- specification/components/examples/UploadScrBundle.json
- specification/components/schemas/CompositionEntry.yaml
- specification/components/schemas/ConditionEntry.yaml
- specification/components/schemas/DeviceEntry.yaml
- specification/components/schemas/DocumentReference.yaml
- specification/components/schemas/DocumentReferenceBundle.yaml
- specification/components/schemas/EncounterParticipantEntry.yaml
- specification/components/schemas/GetScrBundle.yaml
- specification/components/schemas/ObservationEntry.yaml
- specification/components/schemas/OrganizationEntry.yaml
- specification/components/schemas/PartNhsNumber.yaml
- specification/components/schemas/PatientDocumentRefEntry.yaml
- specification/components/schemas/PatientEntry.yaml
- specification/components/schemas/PractitionerEntry.yaml
- specification/components/schemas/PractitionerRoleEntry.yaml
- specification/components/schemas/RelatedPersonEntry.yaml
- specification/components/schemas/UploadBundle.yaml
- specification/components/schemas/compositionAuthor.yaml
- specification/components/schemas/compositionSection.yaml
- specification/components/schemas/compositionSubject.yaml
- specification/summary-care-record.yaml
> NIAD-1131 OAS updates; using Snomed URL in FHIR instead of OID

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/HtmlParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/AcsResponse.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/EventListQueryResponse.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/UploadScrService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/TemplateUtils.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/XmlUtils.java
> NIAD-1139 Vulnerabilities detected by Sonar fixed

- manifest_template.yml
-------
This PR adds a manifest_template.yml file, which is template expanded into a manifest.yml as part of the build pipeline. This file defines all products/specs deployed to apigee in PRs/release pipelines.
> APM-1572 Add manifest_template.yml to repository

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/logging/LoggingAspect.java
> NIAD-1145 Temporarily enabled logging of method execution times in INFO

- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ApacheHttpClientConfig.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/SpineConfiguration.java
- docker/service/src/main/resources/application.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
> NIAD-1149 do not set up TLS in Sandbox mode

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineHttpClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineResponseHandler.java
> NIAD-1141 Spine response handling extracted; additional logging

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SandboxSpineClient.java
> NIAD-1141 sandbox fix

- Makefile
- docker/service/src/integration-test/resources/application.yml
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SandboxSpineClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/FhirParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ScrConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ScrSpringConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/SendScrController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/BundleMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/UploadScrService.java
- docker/service/src/main/resources/application.yml
- ecs-proxies-deploy.yml
> NIAD-1141 additional logging; scaling rules

- Makefile
> NIAD-1141 restore real spine connection in REF

- specification/summary-care-record.yaml
> NIAD-1184 Sandbox test scenarios - fixed OAS rendering

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/xml/Device.java
- docker/service/src/main/resources/templates/partials/Device.mustache
- specification/components/schemas/DeviceEntry.yaml
> Niad 1224 device type validation

- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
> NIAD-1207 /AuditEvent error handling - unsupported HTTP method

- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
> Niad 1208 handle author null address

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
> Niad 1209 set consent validate nhs number presence

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
> Niad 1211 alert agent role validation

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
> Niad 1212 agent requestor validation

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
- specification/components/schemas/DeviceEntry.yaml
> Niad 1222 device note should be optional

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/OperationOutcomeExceptionHandler.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/xml/Device.java
- docker/service/src/main/resources/templates/partials/Device.mustache
- specification/components/schemas/DeviceEntry.yaml
> Niad 1223 device version should be optional

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ObservationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- specification/components/schemas/DeviceEntry.yaml
- specification/components/schemas/ObservationEntry.yaml
> Niad 1231 related person name validation

- specification/components/schemas/DeviceEntry.yaml
> NIAD-1226 device.name is optional

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- specification/components/schemas/DeviceEntry.yaml
> Niad 1228 device id should be optional

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- specification/components/schemas/OrganizationEntry.yaml
- specification/components/schemas/RelatedPersonEntry.yaml
> Niad 1234 org identifier validation

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
> NIAD-1232 RelatedPerson relationship validation

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/CompositionMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ConditionMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ObservationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/PatientMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/GpSummary.java
- specification/components/schemas/CompositionEntry.yaml
- specification/components/schemas/EncounterParticipantEntry.yaml
- specification/components/schemas/OrganizationEntry.yaml
- specification/components/schemas/PractitionerEntry.yaml
- specification/components/schemas/UploadBundle.yaml
> Niad 1255 bundle id should be optional

- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- proxies/live/apiproxy/targets/scr-target.xml
- proxies/sandbox/apiproxy/policies/KeyValueMapOperations.GetAsid.xml
> APM-1980 Auto-Populate ASID in INT

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/GetScrUAT.java
- docker/service/src/integration-test/resources/bundle.fhir.json
- docker/service/src/integration-test/resources/uat/get_scr/success/1-basic.response.json
- docker/service/src/integration-test/resources/uat/responses/event-list-query/success.xml
- docker/service/src/integration-test/resources/uat/responses/event-query/success.xml
- docker/service/src/integration-test/resources/uat/upload_scr/no_consent/1-dissent.request.json
- docker/service/src/integration-test/resources/uat/upload_scr/success/1-basic.request.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/CompositionMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/GpSummaryMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/HtmlParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/XmlToFhirMapper.java
- docker/service/src/main/resources/mock-spine/event-list-query/success.xml
- docker/service/src/main/resources/mock-spine/event-query/success.xml
- docker/service/src/main/resources/templates/partials/AgentDevice.mustache
- docker/service/src/test/resources/html_parser/example.json
- specification/components/examples/GetScrBundle.json
- specification/components/examples/UploadScrBundle.json
- specification/components/schemas/PractitionerRoleEntry.yaml
> Niad 1267 date parsing and section mapping

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- specification/components/schemas/GetScrBundle.yaml
- specification/components/schemas/PractitionerEntry.yaml
- specification/components/schemas/RelatedPersonEntry.yaml
- specification/components/schemas/UploadBundle.yaml
> NIAD-1273 practitioner name mapping simplified

- docker/service/src/integration-test/resources/bundle.fhir.json
- docker/service/src/integration-test/resources/uat/get_scr/success/1-basic.response.json
- docker/service/src/integration-test/resources/uat/upload_scr/bad_request/1-missingComposition.request.json
- docker/service/src/integration-test/resources/uat/upload_scr/no_consent/1-dissent.request.json
- docker/service/src/integration-test/resources/uat/upload_scr/success/1-basic.request.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ParticipantAgentMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/OrganisationMapper.java
- specification/components/examples/GetScrBundle.json
- specification/components/examples/UploadScrBundle.json
- specification/components/schemas/OrganizationEntry.yaml
> NIAD-1273 organization address - supporting text only

- docker/service/src/integration-test/resources/uat/set_acs/bad_request/1-nhsNumberMissing.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/acs/AcsRequestValidator.java
> NIAD-1209 Error message changed to be more clear

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineHttpClient.java
> NIAD-1290 case insensitive spine response headers reading

- Makefile
> NIAD-1291 connect to real Spine in REF env

- specification/summary-care-record.yaml
> Move from Alpha to Beta

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/UploadScrUAT.java
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/common/CustomArgumentsProvider.java
- docker/service/src/integration-test/resources/uat/responses/event-list-query/notFound.xml
- docker/service/src/integration-test/resources/uat/upload_scr/not_found/1-basic.request.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentDeviceMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/AgentPersonMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/DeviceMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/DiagnosisMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/FindingMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/GpSummaryMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/NonAgentRoleMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/OrganisationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/OrganisationSdsMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/ParticipantMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/EventListQueryResponseParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/XmlUtils.java
> Niad 1308 handle case not found spine

- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
> NIAD-1299 log incoming xml responses in debug

- azure/azure-pr-pipeline.yml
- proxies/live/apiproxy/policies/KeyValueMapOperations.GetDefaultAsid.xml
- proxies/live/apiproxy/targets/scr-target.xml
> Fixed default ASID logic

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineClient.java
> NIAD-1322 spine errors logging

- docker/service/src/integration-test/resources/bundle.fhir.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ConditionMapper.java
- specification/components/schemas/ConditionEntry.yaml
> NIAD-1323 handle no Condition clinicalStatus

- ecs-proxies-deploy.yml
> NIAD-1328 debug logs in INT env

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/WireMockInitializer.java
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/GetScrIdUAT.java
- docker/service/src/integration-test/resources/application.yml
- docker/service/src/integration-test/resources/uat/get_scr_id/success/1-basic.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/identity/IdentityServiceClient.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/IdentityServiceConfiguration.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/config/ScrSpringConfiguration.java
- docker/service/src/main/resources/application.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
> Niad 1336 use internal apigee host

- docker/service/src/integration-test/resources/application.yml
- docker/service/src/main/resources/application.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
> use egress hosts for apigee

- docker/service/src/main/resources/templates/REPC_RM150007UK05.mustache
> NIAD-1341 correct excerptFrom/templateId/extension value

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineClient.java
> NIAD-1379 UTF-8 encoding in Spine requests

- specification/summary-care-record.yaml
> Re-branding NHS Identity to NHS CIS2

- .github/workflows/pr-lint.yaml
- proxies/live/apiproxy/policies/AssignMessage.CatchallErrorMessage.xml
- proxies/live/apiproxy/policies/AssignMessage.Errors.Default.xml
- proxies/live/apiproxy/policies/AssignMessage.Errors.UserRoleSharedFlow.xml
- proxies/live/apiproxy/policies/FlowCallout.UserRoleService.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/targets/scr-target.xml
- proxies/sandbox/apiproxy/targets/sandbox.xml
- specification/summary-care-record.yaml
> AMB-613 Initial pull request

- specification/summary-care-record.yaml
> NIAD-1502 portal documentation update

- specification/components/schemas/OperationOutcome.yaml
**Descriptiom**
Remove readOnly label from response schemas.
More detail in: [ADZ-894](https://nhsd-jira.digital.nhs.uk/browse/ADZ-894)
> APM-0000 Maps ADZ-894 Remove readOnly label from responde schema

- specification/summary-care-record.yaml
> NIAD-1633: Dummy change to check if spec is published

- .github/workflows/continuous-integration.yml
> NIAD-1893 caching poetry packages restored

- docker/service/Dockerfile
- docker/service/build.gradle
- docker/service/gradle/wrapper/gradle-wrapper.properties
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/GetScrUAT.java
- docker/service/src/integration-test/resources/uat/get_scr_id/success/1-basic.response.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/GetScrController.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/BadRequestException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/ForbiddenException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
- specification/components/examples/DocumentReferenceBundle.json
- specification/components/schemas/DocumentReference.yaml
- specification/summary-care-record.yaml
- tests/api_tests.py
> NIAD-1930 GET SCR ID query params rework

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineClient.java
> NIAD-1954 log successful Spine response statuses

- tests/api_tests.py
> NIAD-1953 auth token test

- specification/summary-care-record.yaml
> NIAD-1962 document examples of HTTP 503

- specification/summary-care-record.yaml
> NIAD-1965 error response examples

- specification/summary-care-record.yaml
> Niad 1965 update error response examples spec

- specification/summary-care-record.yaml
> NIAD-1968 Update description of HTTP 504 error

- specification/summary-care-record.yaml
> NIAD-1971: Update spec according to SCR team comments

- specification/summary-care-record.yaml
> Apm 0001 reorder endpoints

- manifest_template.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2869
Associating the relevant products that can use mock-oauth with the corrisponding identity-service proxy
> APM-2869 Associate products with mock oauth identity-service

- docker/service/src/integration-test/resources/uat/upload_scr/success/2-bulk.request.json
- docker/service/src/integration-test/resources/uat/upload_scr/success/3-bulk-sds.request.json
> NIAD-2013 additional tests - author as organization

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/identity/IdentityServiceClient.java
> NIAD-2064 additional debug logs

- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/identity/IdentityServiceClient.java
- ecs-proxies-deploy.yml
> Niad 2064 additional debug logs

- specification/summary-care-record.yaml
> Fixed incorrect link as part of ASZ-1940

- docker/service/build.gradle
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/component/ScrTest.java
> NIAD-2087 Spring Boot upgrade

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/GetScrUAT.java
- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/common/CustomArgumentsProvider.java
- docker/service/src/integration-test/resources/uat/get_scr/agent_person_author_success/1-basic.response.json
- docker/service/src/integration-test/resources/uat/responses/event-query/agent-person-author-success.xml
> NIAD-2106 additional tests

- azure/templates/run-tests-int.yml
> typo fix on env path

- azure/azure-release-pipeline.yml
- manifest_template.yml
> add prod to manifest and release pipeline

- azure/azure-release-pipeline.yml
- manifest_template.yml
> Niad 2283 pipelines

- Makefile
- ecs-proxies-deploy-prod.yml
> prod - ecs yaml

- manifest_template.yml
> updated prod env quota for future-proofing

- docker/service/build.gradle
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/BadRequestException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/exceptions/ForbiddenException.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/InvestigationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/InvestigationsMapper.java
- docker/service/src/main/resources/templates/partials/Investigation.mustache
- docker/service/src/main/resources/templates/partials/Investigations.mustache
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/fhir/InvestigationTest.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/InvestigationsTest.java
- docker/service/src/test/java/uk/nhs/utils/InvestigationMapperArgumentsProvider.java
- docker/service/src/test/resources/investigation/example.html
- docker/service/src/test/resources/investigation/example.json
> Niad 2313 - Investigations Mapping

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/FindingMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/FindingsMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
- docker/service/src/main/resources/templates/partials/ClinicalObservationsAndFindings.mustache
- docker/service/src/main/resources/templates/partials/Finding.mustache
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/fhir/FindingMapperTest.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/FindingsMapperTest.java
- docker/service/src/test/java/uk/nhs/utils/FindingMapperArgumentsProvider.java
- docker/service/src/test/resources/finding/example.html
- docker/service/src/test/resources/finding/example.json
- docker/service/src/test/resources/finding/expected/expected.html
> NIAD-2311: 'Clinical Observations and Findings' mapped FHIR <-> HL7

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/SetAcsUAT.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/identity/IdentityServiceClient.java
fixed test to more appropriately test this case
> Handle Error more gracefully and in an expected way

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/SocialOrPersonalCircumstanceMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/SocialOrPersonalCircumstancesMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/GpSummary.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/xml/SocialOrPersonalCircumstance.java
- docker/service/src/main/resources/templates/partials/SocialOrPersonalCircumstance.mustache
- docker/service/src/main/resources/templates/partials/SocialOrPersonalCircumstances.mustache
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/fhir/SocialOrPersonalCircumstanceMapperTest.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/SocialOrPersonalCircumstancesMapperTest.java
- docker/service/src/test/resources/social_personal_circumstances/example.html
- docker/service/src/test/resources/social_personal_circumstances/example.json
Mapped social or personal circumstances to and from HL7/FHIR
* [] Dev
> Mapped social or personal circumstances to and from HL7/FHIR

- specification/summary-care-record.yaml
> AMP-941 API Specs - add Errors section

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/CareProfessionalDocumentationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/CareProfessionalDocumentationsMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/PatientAndCarerCorrespondenceMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/common/CodedEntry.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/common/CodedEntryMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/GpSummary.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/xml/CareProfessionalDocumentation.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/utils/DateUtil.java
- docker/service/src/main/resources/templates/partials/CareProfessionalDocumentation.mustache
- docker/service/src/main/resources/templates/partials/CareProfessionalDocumentations.mustache
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/fhir/CareProfessionalDocumentationMapperTest.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/CareProfessionalDocumentationsMapperTest.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/PatientAndCarerCorrespondenceMapperTest.java
- docker/service/src/test/resources/care-professional-documentation/example.html
- docker/service/src/test/resources/care-professional-documentation/example.json
- docker/service/src/test/resources/patient_carer_correspondence/example.json
Added mapping for Care Professional Documentation
Adding missing category from Patient/Carer Correspondence Mapper
> NIAD-2321 care professional documentation

- azure/templates/run-tests-int.yml
- azure/templates/run-tests.yml
- tests/configuration/config.py
- tests/utils/authenticator.py
> remove authenticate url

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/RiskToPatientMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/RisksToPatientMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/models/xml/RiskToPatient.java
- docker/service/src/main/resources/templates/partials/RiskToPatient.mustache
- docker/service/src/main/resources/templates/partials/RisksToPatient.mustache
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/fhir/RiskToPatientMapperTest.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/RisksToPatientMapperTest.java
- docker/service/src/test/resources/risk_to_patient/example.html
- docker/service/src/test/resources/risk_to_patient/example.json
> NIAD-2307 Risk to patient mapped

- .github/workflows/continuous-integration.yml
- docker/service/src/main/resources/templates/partials/Diagnosis.mustache
- docker/service/src/test/resources/diagnosis/example.html
- docker/service/src/test/resources/diagnosis/expected/expected.html
> test file change for Diagnosis mapping - OBS->CON map type

- docker/sds-api/integration-tests/Pipfile.lock
- package-lock.json
- package.json
- poetry.lock
Upgraded all packages previously flagged as being outdated.
> Niad 2527 npm updates

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/ObservationMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
> Niad 2315 additional family history functionality

- specification/summary-care-record.yaml
Documentation updated to include Production Beta Status
> Niad 2564 documentation updates

- docker/service/src/integration-test/resources/uat/send_alert/bad_request/1-missingNhsNumber.request.json
- docker/service/src/integration-test/resources/uat/send_alert/bad_request/3-multipleOrgEntry.request.json
- docker/service/src/integration-test/resources/uat/send_alert/spine_error/1-invalidValue.request.json
- docker/service/src/integration-test/resources/uat/send_alert/success/1-basic.request.json
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/test/resources/alert/subtype_range.json
- docker/service/src/test/resources/alert/success.json
- docker/service/src/test/resources/alert/type_range.json
- docker/service/src/test/resources/alert/type_subtype_combination_24.json
- docker/service/src/test/resources/alert/type_subtype_combination_26.json
- specification/components/examples/AuditEvent.json
- specification/components/schemas/AuditEvent.yaml
- tests/non_prod/test_data/audit_event.json
Updated specification details on the alert endpoint alert type specifications. 
> Niad 2584 alert spec reference updates

- azure/templates/run-tests-int.yml
> fix smoke tests (int)

- specification/summary-care-record.yaml
Broken Hyperiink fix added identified in live review. 
> NIAD-2564: hyperlink fix on the specification text

- .github/workflows/pr-lint.yaml
- CONTRIBUTING.md
- README.md
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline-main.yml
- azure/azure-release-pipeline-master.yml
- azure/azure-release-pipeline.yml
- specification/summary-care-record.yaml
> Niad 2592 deployment

- CONTRIBUTING.md
- README.md
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
> fixing pipeline changes undid by merge

- .github/pull_request_template.md
> Updated the pr template.

- docker/service/src/test/resources/gp_summary/from/fhir/additionalinfo/lifestyle.json
We have found that "Lifestyle" will not be accepted by spine as a valid value. This change will make it so the test data matches our real-world testing.
> Corrected the test data for lifestyle headers.

- specification/summary-care-record.yaml
Added app restricted authorisation documentation and fixed rapidoc formatting.
> Added app restricted authorisation documentation and fixed rapidoc formatting.

- azure/azure-release-pipeline-master.yml
- azure/azure-release-pipeline.yml
- azure/templates/run-tests-int.yml
> Niad 2722 pipeline restructure

- tests/prod/api_tests.py
Having a test check the commit ID against environment variables is not good practice we believe, hence is getting removed.
> Removed commit id assert from smoketests.

- tests/non_prod/api_tests.py
Added the new app restricted internal dev key to smoke tests.
> Updating the smoketests to the new Internal Dev App Restricted app.

- azure/azure-pr-pipeline.yml
Removed internal-dev sandbox environment from the pipeline. It's not used and it slows things down.
> Removed the internal-dev-sandbox environment from the pipeline.

- specification/summary-care-record.yaml
Small correction to the documentation.
> Small correction to the documentation.

- specification/summary-care-record.yaml
Added disallowed combinations of type and subtype in the alerts endpoint documentation.
> Added explanation of alerts endpoint validation.

- azure/azure-pr-pipeline.yml
Added sandbox environment back. The smoketest should now be skipped in sandbox.
> Niad 2723 sandbox env

- specification/summary-care-record.yaml
Adding exponential backoff documentation.
> Niad 1496 various documentation updates

- package-lock.json
- package.json
- specification/summary-care-record.yaml
I've also changed Speccy to a fork of my own where I updated only the affected version of ejs and changed the redoc dependency to be a solid version rather than a release candidate. See [my github](https://github.com/stevenmccullaghmadetech/speccy/commits/master) for exact changes. 
> Niad 2704 dependabot

- specification/summary-care-record.yaml
Removed misleading text saying that an argument is optional when it is not.
> Removed misleading text for header parameter.

- poetry.lock
- pyproject.toml
Removed the old AIM Apigee package as it's deprecated.
> Removed the old APIM package.

- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidator.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/controllers/validation/alert/AlertRequestValidatorTests.java
- docker/service/src/test/resources/alert/free_text.json
- docker/service/src/test/resources/alert/free_text_empty.json
- docker/service/src/test/resources/alert/free_text_wrong_subtype.json
Added outcomeDesc field to the alert endpoint for free text.
> Added outcomeDesc field to the Alert endpoint.

- docker/service/src/integration-test/java/uk/nhs/adaptors/scr/uat/SetAcsUAT.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/controllers/fhir/AcsController.java
- tests/non_prod/conftest.py
Test to see if this resolves the core problem. We can then re-add the integration tests.
> Add test fix with removed integration tests

- tests/non_prod/conftest.py
> Adding comment explaining auth bypass

- docker/service/src/main/java/uk/nhs/adaptors/scr/models/GpSummary.java
> Additional information.

- README.md
> Fix Build badge on README

- docker/service/src/main/java/uk/nhs/adaptors/scr/components/FhirParser.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/hl7/XmlToFhirMapper.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/AcsService.java
- docker/service/src/main/java/uk/nhs/adaptors/scr/services/GetScrService.java
- docker/service/src/test/java/uk/nhs/adaptors/scr/mappings/from/hl7/XmlToFhirMapperTest.java
Conversion of all dates and times that come through the SCR api into GMT.
> Added conversions to GMT timezones.

- specification/summary-care-record.yaml
> Remove network access documentation

- specification/summary-care-record.yaml
Changing documentation urls from http to https
> Updating urls to https where possible

- docker/service/src/main/java/uk/nhs/adaptors/scr/mappings/from/fhir/SocialOrPersonalCircumstanceMapper.java
> Comment change for testing pipeline.

- .github/workflows/build.yaml
- docker/service/build.gradle
- docker/service/src/main/java/uk/nhs/adaptors/scr/clients/spine/SpineClient.java
Adding sonar cloud config and relevant build.yaml
> Adding sonar cloud config and relevant build.yaml

- README.md
- poetry.lock
> NIAD-3100_2328764

- Pipfile
- specification/summary-care-record.yaml
Changing small wording in documentation
> Updating documentation language

- ecs-proxies-deploy.yml
Updating PTL first. Once successful prod should be updated
> APM-5356 update SCR with new G2 LDAP certs 

- ecs-proxies-deploy-prod.yml
> APM-5356 update SCR SDS container with new G2 certs for prod

- specification/summary-care-record.yaml
> Updated published version number

- specification/summary-care-record.yaml
Incremental git tag version update
> Niad 3120 improve versioning

- specification/summary-care-record.yaml
> Updating release version

- .gitignore
- docker/service/src/main/java/uk/nhs/adaptors/scr/components/FhirParser.java
> NIAD-000 fhir parser typo correction

- manifest_template.yml
- proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
- proxies/live/apiproxy/targets/scr-target.xml
> FLAGSAPI-1140 update user restricted scope to be level aal2
